wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694716976.911625
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 53
      - 55
      - 105
      3:
      - 2
      - 13
      - 23
      4: 3.10.0
      5: 0.15.10
      8:
      - 3
      - 5
